version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: webshop-backend
    ports:
      - "4813:4813"
    volumes:
      - ./backend/data:/app/data
    environment:
      - RUST_LOG=info
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: webshop-frontend
    ports:
      - "4812:4812"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:4813
    depends_on:
      - backend
    restart: unless-stopped